### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AiltonOliveir** [BIT-Zhaoyao/LSTM_BT#1]
Could you please put the input files ?

**Comment by BIT-Zhaoyao** [comment]
> Could you please put the input files ?

I have uploaded the dataset I use in the paper on Google drive. The link is https://drive.google.com/file/d/1R--q5pVpFIB4Uu3sl_StcopnIeruocX8/view?usp=drive_link

**Comment by AiltonOliveir** [comment]
Hi unfortunately the link is private and need to ask request to access. I Suggest you let it "open to view"
Thanks again for your work
